version: "3"

services:
  asvz-bot:
    container_name: asvz-bot
    image: asvz-bot
    build:
      context: .
    environment:
      # Redirect env values from env files. Consult README.md for more information on how to configure the docker setup.
      # Credential values
      - ASVZ_ORGANIZATION=${ASVZ_ORGANIZATION:-}
      - ASVZ_USERNAME=${ASVZ_USERNAME:-}
      - ASVZ_PASSWORD=${ASVZ_PASSWORD:-}
      # Enrollment type, e.g. training, lesson, event
      - ASVZ_ENROLLMENT_TYPE=${ASVZ_ENROLLMENT_TYPE:-}
      # Lesson values
      - ASVZ_LESSON_ID=${ASVZ_LESSON_ID:-}
      # Training values
      - ASVZ_WEEKDAY=${ASVZ_WEEKDAY:-}
      - ASVZ_START_TIME=${ASVZ_START_TIME:-}
      - ASVZ_FACILITY=${ASVZ_FACILITY:-}
      - ASVZ_LEVEL=${ASVZ_LEVEL:-}
      - ASVZ_SPORT_ID=${ASVZ_SPORT_ID:-}
      - ASVZ_TRAINER=${ASVZ_TRAINER:-}
